In [107]:
import geopandas as gpd
import pandas as pd

In [113]:
# Questions

# In this sheet https://docs.google.com/spreadsheets/d/1TVZTQQ4XZsOtV_CW6yXvdrjH-D1rLMeds1nA5r_Uz_4/edit#gid=738288455
# Is column N or column O method more reliable?

In [109]:
national_crop_boundaries = gpd.read_file("../data/processed/global_crop_boundaries.gpkg")
national_crop_boundaries.head(2)

,ADM0_NAME,apple_sum,oilseednes_sum,cerealnes_sum,hemp_sum,blueberry_sum,peachetc_sum,spicenes_sum,pistachio_sum,chilleetc_sum,...,carrot_sum,barley_sum,mixedgrass_sum,sunflower_sum,bambara_sum,berrynes_sum,maizefor_sum,buckwheat_sum,maize_sum,geometry
0,Afghanistan,185.035309,0.0,0.000000,0.0,0.000000,40.733936,8.637327,4.374868,0.000000,...,187.465988,90113.484375,2232.304443,34.537338,1008.699768,0.821507,755.022278,2.659622,114995.109375,"MULTIPOLYGON (((69.37872 37.39316, 69.37835 37..."
1,Aksai Chin,908.426941,0.0,0.187767,0.0,0.002828,15.938924,10.912670,4.768875,80.012184,...,80.979408,13.978951,0.000000,41.286839,1.286475,0.076794,0.000000,22.660929,24996.886719,"MULTIPOLYGON (((78.94793 33.37869, 78.93791 33..."

In [110]:
lookup = pd.read_csv("../data/processed/residue_lookup.csv", index_col="crop")

In [111]:
lookup.head(2)

       sg_ratio  res_dm_ratio  crude_protein_perc  rum_me  nd_fibre
crop
wheat  1.333333          0.91                 4.2     6.8      77.5
rice   1.200000          0.92                 8.2     7.9      70.0

In [112]:
def get_dry_crop_residue_mass(crop_name, crop_production, lookup):
    if crop_name in lookup.index:
        return lookup.loc[crop_name].sg_ratio * crop_yield * lookup.loc[crop_name].res_dm_ratio
    return 0

In [59]:
for crop_name, lookup_row in lookup.iterrows():
    national_crop_boundaries[f"{crop_name}_dry_residues"] = national_crop_boundaries[f"{crop_name}_sum"].apply(lambda s: get_dry_crop_residue_mass(crop_name, s, lookup))

In [67]:
national_crop_boundaries

,ADM0_NAME,apple_sum,oilseednes_sum,cerealnes_sum,hemp_sum,blueberry_sum,peachetc_sum,spicenes_sum,pistachio_sum,chilleetc_sum,...,apple_dry_residues,tomato_dry_residues,pea_dry_residues,watermelon_dry_residues,oilseedfor_dry_residues,fruitnes_dry_residues,chickpea_dry_residues,mixedgrain_dry_residues,ryefor_dry_residues,olive_dry_residues
0,Afghanistan,185.035309,0.000000,0.000000,0.0,0.000000,40.733936,8.637327,4.374868,0.000000,...,185.035309,6.109177e+02,2608.558105,528.469788,0.000000e+00,77.739975,17193.566406,0.0,0.000000,0.000000
1,Aksai Chin,908.426941,0.000000,0.187767,0.0,0.002828,15.938924,10.912670,4.768875,80.012184,...,908.426941,6.221344e+02,16.645689,372.035950,0.000000e+00,4.848140,1.576527,0.0,0.000000,0.776361
2,Albania,13319.992188,0.000000,0.000000,0.0,0.000000,2064.390137,287.258179,0.000000,389.868866,...,13319.992188,2.393517e+05,8.277140,444.068848,0.000000e+00,0.000000,1.414948,0.0,0.000000,55474.429688
3,Algeria,103359.070312,0.000000,110.465332,0.0,0.000000,57623.679688,7.669412,0.030779,169377.093750,...,103359.070312,1.193995e+06,3004.637451,422802.906250,1.968478e+03,39475.968750,13491.037109,0.0,917060.937500,341510.460938
4,American Samoa,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,West Bank,11396.078125,727.380127,15.372060,0.0,106.471436,11088.013672,746.337158,0.000000,19975.939453,...,11396.078125,2.006864e+05,58.707184,91871.171875,6.010307e+00,7322.057129,2297.117676,0.0,0.000000,58567.488281
271,Western Sahara,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.0,0.000000,0.000000
272,Yemen,2387.529297,0.000000,0.000000,0.0,0.000000,2586.659180,0.000000,0.000000,11047.725586,...,2387.529297,3.850711e+05,2273.683594,86074.437500,1.279236e+04,16731.585938,37222.167969,0.0,34396.621094,0.000000
273,Zambia,2.340643,27.940487,7.570743,0.0,0.000000,0.291549,3292.128418,0.000000,0.000000,...,2.340643,3.556997e+04,44.006119,0.000000,0.000000e+00,21641.314453,224.385971,0.0,0.000000,0.000000
274,Zimbabwe,6114.313477,12305.065430,568.067749,0.0,0.000000,1153.067383,602.908142,0.000000,0.000000,...,6114.313477,2.564146e+04,0.725740,50.921848,2.522898e-41,2350.961914,215.532181,0.0,0.000000,0.000000

In [69]:
df = pd.DataFrame(national_crop_boundaries).drop(columns="geometry")
df.to_csv("../data/processed/global_crop_boundaries_with_residues.csv")

In [70]:
global_cattle_boundaries = gpd.read_file("../data/processed/global_cattle_boundaries.gpkg", driver="GPKG")

In [86]:
cattle = global_cattle_boundaries
crops = national_crop_boundaries

In [87]:
cattle = cattle.set_index("ADM0_NAME")
crops = crops.set_index("ADM0_NAME")

In [90]:
cattle.head(2)
# crops.head(2)

,cattle_count_2017,cattle_count_2006,diff,ratio,geometry
ADM0_NAME,,,,,
Afghanistan,4977000,3983486,993514,1.249408,"MULTIPOLYGON (((7723204.005 3853738.634, 77219..."
Aksai Chin,0,0,0,1.000000,"MULTIPOLYGON (((8788443.589 3490286.778, 87825..."

In [ ]:
crops["cattle_count_2017"] = cattle.cattle_count_2017

In [104]:
crops.drop(columns=["geometry"]).to_csv("../data/processed/global_crop_boundaries_with_residues_and_cattle_count.csv")

In [103]:
crops.geometry

ADM0_NAME
Afghanistan       MULTIPOLYGON (((69.37872 37.39316, 69.37835 37...
Aksai Chin        MULTIPOLYGON (((78.94793 33.37869, 78.93791 33...
Albania           MULTIPOLYGON (((19.82989 42.46665, 19.83127 42...
Algeria           MULTIPOLYGON (((9.57535 30.24043, 9.54563 30.2...
American Samoa    MULTIPOLYGON (((-170.76180 -14.38248, -170.764...
                                        ...
West Bank         MULTIPOLYGON (((35.22752 31.74469, 35.22660 31...
Western Sahara    MULTIPOLYGON (((-8.67028 27.66211, -8.67207 27...
Yemen             MULTIPOLYGON (((42.54285 15.56398, 42.53504 15...
Zambia            MULTIPOLYGON (((30.80741 -8.31065, 30.80741 -8...
Zimbabwe          MULTIPOLYGON (((30.41826 -15.61757, 30.42172 -...
Name: geometry, Length: 275, dtype: geometry